##
##  Makefile -- Build procedure for sample log_syslog Apache module
##  Autogenerated via ``apxs -n log_syslog -g''.
##

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: mod_log_syslog.la

#   compile the DSO file
mod_log_syslog.la: mod_log_syslog.c
	$(APXS) -c $(DEFS) $(INCLUDES) $(LIBS) mod_log_syslog.c

#   install the DSO file into the Apache installation
#   and activate it in the Apache configuration
install: all
	$(APXS) -i -a -n 'log_syslog' mod_log_syslog.la

#   cleanup
clean:
	-rm -f mod_log_syslog.o mod_log_syslog.lo mod_log_syslog.slo mod_log_syslog.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/log_syslog

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

